### ISSUE TITLE
Problem on startup

### ISSUE THREAD

**Issue by ScriptShot** [uklance/tapestry-atmosphere#32]
Hi, 

can someone help me with this? Unfortunately, I do not really know what to ask. I use gradle to integrate the repository here from github.
maven {
      url 'https://jitpack.io'
}
dependencies {
      implementation 'com.github.uklance: tapestry-atmosphere: master-SNAPSHOT'
}

`ERROR [org.apache.catalina.core.ContainerBase.[myApp].[localhost].[/path]] [main ] Exception starting filter [myApp] - [org.apache.catalina.core.StandardContext]
java.lang.NoClassDefFoundError: org/apache/tapestry5/ioc/ServiceBinder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
	at java.base/java.lang.Class.getMethods(Class.java:1905)
	at org.apache.tapestry5.ioc.internal.DefaultModuleDefImpl.<init>(DefaultModuleDefImpl.java:126)
	at org.apache.tapestry5.ioc.RegistryBuilder.add(RegistryBuilder.java:123)
	at org.apache.tapestry5.ioc.RegistryBuilder.add(RegistryBuilder.java:161)
	at org.apache.tapestry5.ioc.IOCUtilities.addModulesInList(IOCUtilities.java:132)
	at org.apache.tapestry5.ioc.IOCUtilities.addModulesInManifest(IOCUtilities.java:105)
	at org.apache.tapestry5.ioc.IOCUtilities.addDefaultModules(IOCUtilities.java:76)
	at org.apache.tapestry5.internal.TapestryAppInitializer.<init>(TapestryAppInitializer.java:97)
	at org.apache.tapestry5.TapestryFilter.init(TapestryFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4530)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5169)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:456)
	at com.john.smith.web.EclipseMain.run(EclipseMain.java:279)
	at com.john.smith.web.EclipseMain.main(EclipseMain.java:123)
Caused by: java.lang.ClassNotFoundException: org.apache.tapestry5.ioc.ServiceBinder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 41 more
15:35:57.479 ERROR [org.apache.catalina.core.StandardContext] [main ] One or more Filters failed to start. Full details will be found in the appropriate container log file - [org.apache.catalina.core.StandardContext]
15:35:57.479 ERROR [org.apache.catalina.core.StandardContext] [main ] Context [/path] startup failed due to previous errors - [org.apache.catalina.core.StandardContext]`

**Comment by ScriptShot** [comment]
Knock Knock....

**Comment by uklance** [comment]
Jars are here
https://github.com/uklance/releases/tree/master/org/lazan/tapestry-atmosphere/0.0.6
